### ISSUE TITLE
Amjayy:v

### ISSUE THREAD

**Issue by MFarelS** [Bintang73/botst4rz#1]
![IMG-20201030-WA0272](https://user-images.githubusercontent.com/58540890/97645257-00b59100-1a7f-11eb-9480-52ed7533e9fb.jpg)
:v

**Comment by binskyi** [comment]
Anjay gurinjay makan bajay

**Comment by MFarelS** [comment]
> Anjay gurinjay makan bajay

Awokwaokwaokwaok
