### ISSUE TITLE
Bot Nulis Error

### ISSUE THREAD

**Issue by aditalf** [Bintang73/botst4rz#2]
Bot Nulis Masih Error?

**Comment by binskyi** [comment]
sudah saya perbarui, silahkan cek kembali

**Comment by niizam** [comment]
> sudah saya perbarui, silahkan cek kembali
masih error bro

**Comment by Ntahlah75** [comment]
Respon dari apinya cuma `result: string` ama `status: number`, string enggak ada property data, mungkin karena itu jadi error bang
