### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by ben-dev2609** [Bintang73/botst4rz#8]
bang request dong: PREFIX nya bisa di ganti

**Comment by ben-dev2609** [comment]
btw kok nulis error ya?

**Comment by LensKase23** [comment]
kok gak bisa download lagu?

**Comment by bangnopal** [comment]
> btw kok nulis error ya?

Error gimana itu?

**Comment by binskyi** [comment]
udah saya fix, silahkan hapus data termux dan ulangi dari awal
